"""
NotesOS Models - Note Related Models
"""

import uuid
from datetime import datetime
from enum import Enum
from sqlalchemy import (
    Column,
    String,
    Boolean,
    DateTime,
    Text,
    Integer,
    ForeignKey,
    Enum as SQLEnum,
    Numeric,
)
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship
from pgvector.sqlalchemy import Vector

from app.database import Base


class ContentType(str, Enum):
    TEXT = "text"
    PDF = "pdf"
    IMAGE = "image"


class VerificationStatus(str, Enum):
    VERIFIED = "verified"
    DISPUTED = "disputed"
    UNVERIFIED = "unverified"


class Note(Base):
    """Note model - user-uploaded study materials."""

    __tablename__ = "notes"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    topic_id = Column(UUID(as_uuid=True), ForeignKey("topics.id"), nullable=False)
    uploaded_by = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)

    title = Column(String(255), nullable=False)
    content = Column(Text, nullable=False)
    content_type = Column(
        SQLEnum(ContentType), default=ContentType.TEXT, nullable=False
    )
    file_url = Column(Text, nullable=True)

    # Fact-checking status
    is_verified = Column(Boolean, default=False, nullable=False)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(
        DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False
    )

    # Relationships
    topic = relationship("Topic", back_populates="notes")
    chunks = relationship(
        "NoteChunk", back_populates="note", cascade="all, delete-orphan"
    )
    versions = relationship(
        "NoteVersion", back_populates="note", cascade="all, delete-orphan"
    )
    fact_checks = relationship(
        "FactCheck", back_populates="note", cascade="all, delete-orphan"
    )


class NoteChunk(Base):
    """Note chunks for RAG - stores text with vector embeddings."""

    __tablename__ = "note_chunks"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    note_id = Column(UUID(as_uuid=True), ForeignKey("notes.id"), nullable=False)

    chunk_text = Column(Text, nullable=False)
    chunk_index = Column(Integer, nullable=False)

    # Vector embedding for similarity search (1024 dimensions for Voyage AI)
    embedding = Column(Vector(1024), nullable=True)

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationships
    note = relationship("Note", back_populates="chunks")


class NoteVersion(Base):
    """Note version history for edit tracking."""

    __tablename__ = "note_versions"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    note_id = Column(UUID(as_uuid=True), ForeignKey("notes.id"), nullable=False)
    content = Column(Text, nullable=False)
    edited_by = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)
    version_number = Column(Integer, nullable=False)

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationships
    note = relationship("Note", back_populates="versions")


class FactCheck(Base):
    """Fact check results for note claims."""

    __tablename__ = "fact_checks"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    note_id = Column(UUID(as_uuid=True), ForeignKey("notes.id"), nullable=False)

    claim_text = Column(Text, nullable=False)
    verification_status = Column(
        SQLEnum(VerificationStatus),
        default=VerificationStatus.UNVERIFIED,
        nullable=False,
    )

    # Sources as JSONB array
    sources = Column(JSONB, nullable=False, default=[])

    confidence_score = Column(Numeric(3, 2), nullable=True)  # 0.00 - 1.00
    ai_explanation = Column(Text, nullable=True)

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(
        DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False
    )

    # Relationships
    note = relationship("Note", back_populates="fact_checks")


class PreClassResearch(Base):
    """Pre-class research generated by AI for topics."""

    __tablename__ = "pre_class_research"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    topic_id = Column(UUID(as_uuid=True), ForeignKey("topics.id"), nullable=False)

    research_content = Column(Text, nullable=False)
    sources = Column(JSONB, nullable=False, default=[])
    key_concepts = Column(JSONB, nullable=True)

    generated_at = Column(DateTime, default=datetime.utcnow, nullable=False)
