"""generalize audio lessons into audio artifacts

Revision ID: 58ffec46e97b
Revises: 305dbce1c963
Create Date: 2026-07-30 13:27:08.813021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58ffec46e97b'
down_revision: Union[str, None] = '305dbce1c963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('DEFAULT', 'USER_INSTRUCTION', 'REMEDIATION', 'EXAM_FOCUSED', 'SLOWER', 'WORKED_EXAMPLE', name='audiolens').create(op.get_bind())
    sa.Enum('COURSE', 'TOPIC', 'CONCEPT', 'CONCEPT_CLUSTER', name='audioscopetype').create(op.get_bind())
    op.create_table('audio_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scope_type', postgresql.ENUM('COURSE', 'TOPIC', 'CONCEPT', 'CONCEPT_CLUSTER', name='audioscopetype', create_type=False), nullable=False),
    sa.Column('scope_ref', sa.UUID(), nullable=False),
    sa.Column('knowledge_id', sa.UUID(), nullable=True),
    sa.Column('lens', postgresql.ENUM('DEFAULT', 'USER_INSTRUCTION', 'REMEDIATION', 'EXAM_FOCUSED', 'SLOWER', 'WORKED_EXAMPLE', name='audiolens', create_type=False), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('cost_credits', sa.Integer(), nullable=False),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('voice', sa.String(length=50), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='knowledgestatus', create_type=False), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_id'], ['topic_knowledge.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_artifacts_knowledge_id'), 'audio_artifacts', ['knowledge_id'], unique=False)
    op.create_index(op.f('ix_audio_artifacts_owner_id'), 'audio_artifacts', ['owner_id'], unique=False)
    op.create_index(op.f('ix_audio_artifacts_scope_ref'), 'audio_artifacts', ['scope_ref'], unique=False)
    op.create_index(op.f('ix_audio_artifacts_scope_type'), 'audio_artifacts', ['scope_type'], unique=False)
    op.create_index('uq_audio_artifact_global_scope_lens', 'audio_artifacts', ['scope_type', 'scope_ref', 'lens'], unique=True, postgresql_where=sa.text('owner_id IS NULL'))
    # Data backfill (not autogenerated): every existing AudioLesson becomes the shared
    # global, default-lens, topic-scoped artifact it always implicitly was. AudioLesson
    # had no per-topic uniqueness, so regenerations left multiple rows per topic — the
    # new dedup constraint only allows one global artifact per (scope, lens), so only
    # the latest row per topic_id survives (matching the "most recent" query every
    # /audio endpoint already used).
    op.execute(
        """
        INSERT INTO audio_artifacts (
            id, scope_type, scope_ref, knowledge_id, lens, instruction, owner_id,
            cost_credits, script, audio_url, duration_seconds, voice, status,
            error_message, stale, generated_at, created_at, updated_at
        )
        SELECT DISTINCT ON (topic_id)
            id, 'TOPIC', topic_id, knowledge_id, 'DEFAULT', NULL, NULL,
            0, script, audio_url, duration_seconds, voice, status,
            error_message, false, generated_at, created_at, updated_at
        FROM audio_lessons
        ORDER BY topic_id, created_at DESC
        """
    )
    op.drop_index(op.f('ix_audio_lessons_knowledge_id'), table_name='audio_lessons')
    op.drop_index(op.f('ix_audio_lessons_topic_id'), table_name='audio_lessons')
    op.drop_table('audio_lessons')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_lessons',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('topic_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('knowledge_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('script', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('audio_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('voice', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='knowledgestatus', create_type=False), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('generated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['knowledge_id'], ['topic_knowledge.id'], name=op.f('audio_lessons_knowledge_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('audio_lessons_topic_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('audio_lessons_pkey'))
    )
    op.create_index(op.f('ix_audio_lessons_topic_id'), 'audio_lessons', ['topic_id'], unique=False)
    op.create_index(op.f('ix_audio_lessons_knowledge_id'), 'audio_lessons', ['knowledge_id'], unique=False)
    # Reverse backfill: only global, topic-scoped, default-lens artifacts map back to the
    # old shape. Personal artifacts and other scopes/lenses have no AudioLesson equivalent
    # and are dropped on downgrade.
    op.execute(
        """
        INSERT INTO audio_lessons (
            id, topic_id, knowledge_id, script, audio_url, duration_seconds, voice,
            status, error_message, generated_at, created_at, updated_at
        )
        SELECT
            id, scope_ref, knowledge_id, script, audio_url, duration_seconds, voice,
            status, error_message, generated_at, created_at, updated_at
        FROM audio_artifacts
        WHERE scope_type = 'TOPIC' AND lens = 'DEFAULT' AND owner_id IS NULL
            AND knowledge_id IS NOT NULL
        """
    )
    op.drop_index('uq_audio_artifact_global_scope_lens', table_name='audio_artifacts', postgresql_where=sa.text('owner_id IS NULL'))
    op.drop_index(op.f('ix_audio_artifacts_scope_type'), table_name='audio_artifacts')
    op.drop_index(op.f('ix_audio_artifacts_scope_ref'), table_name='audio_artifacts')
    op.drop_index(op.f('ix_audio_artifacts_owner_id'), table_name='audio_artifacts')
    op.drop_index(op.f('ix_audio_artifacts_knowledge_id'), table_name='audio_artifacts')
    op.drop_table('audio_artifacts')
    sa.Enum('COURSE', 'TOPIC', 'CONCEPT', 'CONCEPT_CLUSTER', name='audioscopetype').drop(op.get_bind())
    sa.Enum('DEFAULT', 'USER_INSTRUCTION', 'REMEDIATION', 'EXAM_FOCUSED', 'SLOWER', 'WORKED_EXAMPLE', name='audiolens').drop(op.get_bind())
    # ### end Alembic commands ###
