"""removed v1 Test support

Revision ID: 3d86af752614
Revises: c992b8fa8e83
Create Date: 2026-07-26 19:43:57.146562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d86af752614'
down_revision: Union[str, None] = 'c992b8fa8e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('question_type', sa.String(length=16), nullable=False),
    sa.Column('scope_topic_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('generation_status', sa.String(length=16), nullable=False),
    sa.Column('questions_done', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_tests_course_id'), 'practice_tests', ['course_id'], unique=False)
    op.create_index(op.f('ix_practice_tests_created_by'), 'practice_tests', ['created_by'], unique=False)
    op.create_table('practice_test_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['practice_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_test_questions_concept_id'), 'practice_test_questions', ['concept_id'], unique=False)
    op.create_index(op.f('ix_practice_test_questions_test_id'), 'practice_test_questions', ['test_id'], unique=False)
    op.drop_index(op.f('ix_test_answers_attempt_id'), table_name='test_answers')
    op.drop_index(op.f('ix_test_answers_question_id'), table_name='test_answers')
    op.drop_table('test_answers')
    op.drop_index(op.f('ix_test_questions_test_id'), table_name='test_questions')
    op.drop_table('test_questions')
    op.drop_index(op.f('ix_test_attempts_test_id'), table_name='test_attempts')
    op.drop_index(op.f('ix_test_attempts_user_id'), table_name='test_attempts')
    op.drop_table('test_attempts')
    op.drop_index(op.f('ix_tests_course_id'), table_name='tests')
    op.drop_index(op.f('ix_tests_created_by'), table_name='tests')
    op.drop_table('tests')
    op.drop_column('users', 'phone_verified')
    op.drop_column('users', 'phone_otp')
    op.drop_column('users', 'phone_otp_expires')
    sa.Enum('PRACTICE', 'MOCK', 'SELF_TEST', name='testtype').drop(op.get_bind())
    sa.Enum('MCQ', 'SHORT_ANSWER', 'ESSAY', name='questiontype').drop(op.get_bind())
    sa.Enum('CORRECT', 'PARTIAL', 'NEEDS_REVIEW', name='answerstatus').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('CORRECT', 'PARTIAL', 'NEEDS_REVIEW', name='answerstatus').create(op.get_bind())
    sa.Enum('MCQ', 'SHORT_ANSWER', 'ESSAY', name='questiontype').create(op.get_bind())
    sa.Enum('PRACTICE', 'MOCK', 'SELF_TEST', name='testtype').create(op.get_bind())
    op.add_column('users', sa.Column('phone_otp_expires', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('phone_otp', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('phone_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_table('tests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('test_type', postgresql.ENUM('PRACTICE', 'MOCK', 'SELF_TEST', name='testtype', create_type=False), autoincrement=False, nullable=False),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('question_types', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('question_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_status', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('batches_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('batches_done', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('failure_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('tests_course_id_fkey')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('tests_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tests_pkey'))
    )
    op.create_index(op.f('ix_tests_created_by'), 'tests', ['created_by'], unique=False)
    op.create_index(op.f('ix_tests_course_id'), 'tests', ['course_id'], unique=False)
    op.create_table('test_attempts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('test_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('total_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('max_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name=op.f('test_attempts_test_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('test_attempts_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('test_attempts_pkey'))
    )
    op.create_index(op.f('ix_test_attempts_user_id'), 'test_attempts', ['user_id'], unique=False)
    op.create_index(op.f('ix_test_attempts_test_id'), 'test_attempts', ['test_id'], unique=False)
    op.create_table('test_questions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('test_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('question_type', postgresql.ENUM('MCQ', 'SHORT_ANSWER', 'ESSAY', name='questiontype', create_type=False), autoincrement=False, nullable=False),
    sa.Column('correct_answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer_options', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name=op.f('test_questions_test_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('test_questions_pkey'))
    )
    op.create_index(op.f('ix_test_questions_test_id'), 'test_questions', ['test_id'], unique=False)
    op.create_table('test_answers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('attempt_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('answer_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer_audio_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('transcription', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('ai_feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('encouragement', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('CORRECT', 'PARTIAL', 'NEEDS_REVIEW', name='answerstatus', create_type=False), autoincrement=False, nullable=True),
    sa.Column('key_points_covered', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('key_points_missed', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['test_attempts.id'], name=op.f('test_answers_attempt_id_fkey')),
    sa.ForeignKeyConstraint(['question_id'], ['test_questions.id'], name=op.f('test_answers_question_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('test_answers_pkey'))
    )
    op.create_index(op.f('ix_test_answers_question_id'), 'test_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_test_answers_attempt_id'), 'test_answers', ['attempt_id'], unique=False)
    op.drop_index(op.f('ix_practice_test_questions_test_id'), table_name='practice_test_questions')
    op.drop_index(op.f('ix_practice_test_questions_concept_id'), table_name='practice_test_questions')
    op.drop_table('practice_test_questions')
    op.drop_index(op.f('ix_practice_tests_created_by'), table_name='practice_tests')
    op.drop_index(op.f('ix_practice_tests_course_id'), table_name='practice_tests')
    op.drop_table('practice_tests')
    # ### end Alembic commands ###
