"""user phone_hash

Revision ID: 525088d6dbb1
Revises: 3d86af752614
Create Date: 2026-07-27 12:17:30.563248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '525088d6dbb1'
down_revision: Union[str, None] = '3d86af752614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_phone_hash'), 'users', ['phone_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone_hash'), table_name='users')
    op.drop_column('users', 'phone_hash')
    # ### end Alembic commands ###
