"""capture: AUDIO resource kind + audio source type

Revision ID: d8badee7f31a
Revises: 2d355456bd16
Create Date: 2026-07-12 14:03:46.486385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'd8badee7f31a'
down_revision: Union[str, None] = '2d355456bd16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='resourcetype',
        new_values=['TEXT', 'PDF', 'DOCX', 'IMAGE', 'AUDIO'],
        affected_columns=[TableReference(table_schema='public', table_name='resources', column_name='resource_type')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='sourcetype',
        new_values=['TEXT', 'PDF', 'DOCX', 'HANDWRITTEN', 'PRINTED', 'AUDIO'],
        affected_columns=[TableReference(table_schema='public', table_name='resources', column_name='source_type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='sourcetype',
        new_values=['TEXT', 'PDF', 'DOCX', 'HANDWRITTEN', 'PRINTED'],
        affected_columns=[TableReference(table_schema='public', table_name='resources', column_name='source_type')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='resourcetype',
        new_values=['TEXT', 'PDF', 'DOCX', 'IMAGE'],
        affected_columns=[TableReference(table_schema='public', table_name='resources', column_name='resource_type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
