"""resource synthesized_at

Revision ID: d493b2fe2772
Revises: d8badee7f31a
Create Date: 2026-07-13 00:08:10.055259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd493b2fe2772'
down_revision: Union[str, None] = 'd8badee7f31a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('synthesized_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'synthesized_at')
    # ### end Alembic commands ###
