"""retrieval attempt client_event_id (B6 offline sync)

Revision ID: c992b8fa8e83
Revises: 9aad224787f6
Create Date: 2026-07-13 02:56:50.682913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c992b8fa8e83'
down_revision: Union[str, None] = '9aad224787f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('retrieval_attempts', sa.Column('client_event_id', sa.UUID(), nullable=True))
    op.create_unique_constraint('uq_retrieval_attempt_client_event', 'retrieval_attempts', ['client_event_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_retrieval_attempt_client_event', 'retrieval_attempts', type_='unique')
    op.drop_column('retrieval_attempts', 'client_event_id')
    # ### end Alembic commands ###
