"""consume_events substrate (B1 recognition)

Revision ID: a1fca0528a36
Revises: d493b2fe2772
Create Date: 2026-07-13 01:55:39.704842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1fca0528a36'
down_revision: Union[str, None] = 'd493b2fe2772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('NOTE_VIEW', 'AUDIO_LISTEN', name='consumekind').create(op.get_bind())
    op.create_table('consume_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('kind', postgresql.ENUM('NOTE_VIEW', 'AUDIO_LISTEN', name='consumekind', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consume_events_actor_id'), 'consume_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_consume_events_created_at'), 'consume_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_consume_events_topic_id'), 'consume_events', ['topic_id'], unique=False)
    op.create_index('ix_consume_topic_created', 'consume_events', ['topic_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_consume_topic_created', table_name='consume_events')
    op.drop_index(op.f('ix_consume_events_topic_id'), table_name='consume_events')
    op.drop_index(op.f('ix_consume_events_created_at'), table_name='consume_events')
    op.drop_index(op.f('ix_consume_events_actor_id'), table_name='consume_events')
    op.drop_table('consume_events')
    sa.Enum('NOTE_VIEW', 'AUDIO_LISTEN', name='consumekind').drop(op.get_bind())
    # ### end Alembic commands ###
