"""add_pre_class_research_table

Revision ID: 463a4d33e911
Revises: 012ca46d48b7
Create Date: 2026-02-10 21:46:46.422875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '463a4d33e911'
down_revision: Union[str, None] = '012ca46d48b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classes_invite_code'), table_name='classes')
    op.drop_index(op.f('ix_classes_owner_id'), table_name='classes')
    op.drop_index(op.f('ix_classmates_class_id'), table_name='classmates')
    op.drop_index(op.f('ix_classmates_user_id'), table_name='classmates')
    op.drop_index(op.f('ix_note_files_note_id'), table_name='resource_files')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_note_files_note_id'), 'resource_files', ['resource_id'], unique=False)
    op.create_index(op.f('ix_classmates_user_id'), 'classmates', ['user_id'], unique=False)
    op.create_index(op.f('ix_classmates_class_id'), 'classmates', ['class_id'], unique=False)
    op.create_index(op.f('ix_classes_owner_id'), 'classes', ['owner_id'], unique=False)
    op.create_index(op.f('ix_classes_invite_code'), 'classes', ['invite_code'], unique=False)
    # ### end Alembic commands ###
