"""subject_family add SOCIAL_SCIENCE

Revision ID: 305dbce1c963
Revises: 62cfb1ba95b7
Create Date: 2026-07-30 09:53:37.049031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '305dbce1c963'
down_revision: Union[str, None] = '62cfb1ba95b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='subjectfamily',
        new_values=['STEM', 'LANGUAGE', 'HUMANITIES', 'SOCIAL_SCIENCE', 'GENERAL'],
        affected_columns=[TableReference(table_schema='public', table_name='topics', column_name='subject_family', existing_server_default="'GENERAL'::subjectfamily")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='subjectfamily',
        new_values=['STEM', 'LANGUAGE', 'HUMANITIES', 'GENERAL'],
        affected_columns=[TableReference(table_schema='public', table_name='topics', column_name='subject_family', existing_server_default="'GENERAL'::subjectfamily")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
