"""v2 baseline

Revision ID: ec36e4fead66
Revises: 
Create Date: 2026-07-05 12:05:52.428361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'ec36e4fead66'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Extensions autogenerate does not emit but the schema/app depend on:
    #  - vector: resource_chunks.embedding (VECTOR column)
    #  - pg_trgm: school canonicalisation + proximity fuzzy matching
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schools_normalized_name'), 'schools', ['normalized_name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('university', sa.String(length=255), nullable=True),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('program', sa.String(length=255), nullable=True),
    sa.Column('entry_year', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('study_personality', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('personality_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_school_id'), 'users', ['school_id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('invite_code', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code')
    )
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=False)
    op.create_index(op.f('ix_courses_created_by'), 'courses', ['created_by'], unique=False)
    op.create_index(op.f('ix_courses_school_id'), 'courses', ['school_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('TEST_GRADED', 'AI_SUMMARY_READY', 'INVITE_ACCEPTED', 'RESOURCE_UPLOADED', 'CLASSMATE_JOINED', 'GENERAL', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('terms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('division_type', sa.Enum('SEMESTER', 'TERM', 'QUARTER', 'TRIMESTER', name='divisiontype'), nullable=False),
    sa.Column('division_value', sa.String(length=32), nullable=False),
    sa.Column('study_level', sa.String(length=64), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'label', name='uq_term_user_label')
    )
    op.create_index(op.f('ix_terms_user_id'), 'terms', ['user_id'], unique=False)
    op.create_table('course_enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_enrollment_user_course')
    )
    op.create_index(op.f('ix_course_enrollments_course_id'), 'course_enrollments', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_enrollments_term_id'), 'course_enrollments', ['term_id'], unique=False)
    op.create_index(op.f('ix_course_enrollments_user_id'), 'course_enrollments', ['user_id'], unique=False)
    op.create_table('course_outlines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('outline_content', sa.Text(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('parsed_topics', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_outlines_course_id'), 'course_outlines', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_outlines_uploaded_by'), 'course_outlines', ['uploaded_by'], unique=False)
    op.create_table('tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('test_type', sa.Enum('PRACTICE', 'MOCK', 'SELF_TEST', name='testtype'), nullable=False),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('question_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('generation_status', sa.Enum('pending', 'generating', 'ready', 'failed', name='testgenerationstatus', native_enum=False), nullable=False),
    sa.Column('batches_total', sa.Integer(), nullable=True),
    sa.Column('batches_done', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tests_course_id'), 'tests', ['course_id'], unique=False)
    op.create_index(op.f('ix_tests_created_by'), 'tests', ['created_by'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_course_id'), 'topics', ['course_id'], unique=False)
    op.create_table('ai_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_course_id'), 'ai_conversations', ['course_id'], unique=False)
    op.create_index(op.f('ix_ai_conversations_topic_id'), 'ai_conversations', ['topic_id'], unique=False)
    op.create_index(op.f('ix_ai_conversations_user_id'), 'ai_conversations', ['user_id'], unique=False)
    op.create_table('pre_class_research',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('research_content', sa.Text(), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('key_concepts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pre_class_research_topic_id'), 'pre_class_research', ['topic_id'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.Enum('TEXT', 'PDF', 'DOCX', 'IMAGE', name='resourcetype'), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.Enum('TEXT', 'PDF', 'DOCX', 'HANDWRITTEN', 'PRINTED', name='sourcetype'), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('ocr_cleaned', sa.Boolean(), nullable=False),
    sa.Column('original_ocr_text', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('ocr_provider', sa.String(length=50), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_topic_id'), 'resources', ['topic_id'], unique=False)
    op.create_index(op.f('ix_resources_uploaded_by'), 'resources', ['uploaded_by'], unique=False)
    op.create_table('study_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('session_type', sa.Enum('READING', 'QUIZ', 'PRACTICE', name='sessiontype'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('notes_reviewed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('concepts_covered', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_sessions_topic_id'), 'study_sessions', ['topic_id'], unique=False)
    op.create_index(op.f('ix_study_sessions_user_id'), 'study_sessions', ['user_id'], unique=False)
    op.create_table('test_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_attempts_test_id'), 'test_attempts', ['test_id'], unique=False)
    op.create_index(op.f('ix_test_attempts_user_id'), 'test_attempts', ['user_id'], unique=False)
    op.create_table('test_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('MCQ', 'SHORT_ANSWER', 'ESSAY', name='questiontype'), nullable=False),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('answer_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_questions_test_id'), 'test_questions', ['test_id'], unique=False)
    op.create_table('topic_knowledge',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('consolidated_note', sa.Text(), nullable=True),
    sa.Column('key_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('concepts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='knowledgestatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_knowledge_topic_id'), 'topic_knowledge', ['topic_id'], unique=True)
    op.create_table('user_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('mastery_level', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('total_study_time', sa.Integer(), nullable=False),
    sa.Column('total_attempts', sa.Integer(), nullable=False),
    sa.Column('avg_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_progress_course_id'), 'user_progress', ['course_id'], unique=False)
    op.create_index(op.f('ix_user_progress_topic_id'), 'user_progress', ['topic_id'], unique=False)
    op.create_index(op.f('ix_user_progress_user_id'), 'user_progress', ['user_id'], unique=False)
    op.create_table('ai_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_messages_conversation_id'), 'ai_messages', ['conversation_id'], unique=False)
    op.create_table('audio_lessons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_id', sa.UUID(), nullable=False),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('voice', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='knowledgestatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_id'], ['topic_knowledge.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_lessons_knowledge_id'), 'audio_lessons', ['knowledge_id'], unique=False)
    op.create_index(op.f('ix_audio_lessons_topic_id'), 'audio_lessons', ['topic_id'], unique=False)
    op.create_table('fact_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('verification_status', sa.Enum('VERIFIED', 'DISPUTED', 'UNVERIFIED', name='verificationstatus'), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_checks_resource_id'), 'fact_checks', ['resource_id'], unique=False)
    op.create_table('resource_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_chunks_resource_id'), 'resource_chunks', ['resource_id'], unique=False)
    op.create_table('resource_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_order', sa.Integer(), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('ocr_provider', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_files_resource_id'), 'resource_files', ['resource_id'], unique=False)
    op.create_table('test_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answer_audio_url', sa.Text(), nullable=True),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('encouragement', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('CORRECT', 'PARTIAL', 'NEEDS_REVIEW', name='answerstatus'), nullable=True),
    sa.Column('key_points_covered', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('key_points_missed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['test_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['test_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_answers_attempt_id'), 'test_answers', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_test_answers_question_id'), 'test_answers', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_answers_question_id'), table_name='test_answers')
    op.drop_index(op.f('ix_test_answers_attempt_id'), table_name='test_answers')
    op.drop_table('test_answers')
    op.drop_index(op.f('ix_resource_files_resource_id'), table_name='resource_files')
    op.drop_table('resource_files')
    op.drop_index(op.f('ix_resource_chunks_resource_id'), table_name='resource_chunks')
    op.drop_table('resource_chunks')
    op.drop_index(op.f('ix_fact_checks_resource_id'), table_name='fact_checks')
    op.drop_table('fact_checks')
    op.drop_index(op.f('ix_audio_lessons_topic_id'), table_name='audio_lessons')
    op.drop_index(op.f('ix_audio_lessons_knowledge_id'), table_name='audio_lessons')
    op.drop_table('audio_lessons')
    op.drop_index(op.f('ix_ai_messages_conversation_id'), table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index(op.f('ix_user_progress_user_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_topic_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_course_id'), table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index(op.f('ix_topic_knowledge_topic_id'), table_name='topic_knowledge')
    op.drop_table('topic_knowledge')
    op.drop_index(op.f('ix_test_questions_test_id'), table_name='test_questions')
    op.drop_table('test_questions')
    op.drop_index(op.f('ix_test_attempts_user_id'), table_name='test_attempts')
    op.drop_index(op.f('ix_test_attempts_test_id'), table_name='test_attempts')
    op.drop_table('test_attempts')
    op.drop_index(op.f('ix_study_sessions_user_id'), table_name='study_sessions')
    op.drop_index(op.f('ix_study_sessions_topic_id'), table_name='study_sessions')
    op.drop_table('study_sessions')
    op.drop_index(op.f('ix_resources_uploaded_by'), table_name='resources')
    op.drop_index(op.f('ix_resources_topic_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_pre_class_research_topic_id'), table_name='pre_class_research')
    op.drop_table('pre_class_research')
    op.drop_index(op.f('ix_ai_conversations_user_id'), table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_topic_id'), table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_course_id'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_topics_course_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_tests_created_by'), table_name='tests')
    op.drop_index(op.f('ix_tests_course_id'), table_name='tests')
    op.drop_table('tests')
    op.drop_index(op.f('ix_course_outlines_uploaded_by'), table_name='course_outlines')
    op.drop_index(op.f('ix_course_outlines_course_id'), table_name='course_outlines')
    op.drop_table('course_outlines')
    op.drop_index(op.f('ix_course_enrollments_user_id'), table_name='course_enrollments')
    op.drop_index(op.f('ix_course_enrollments_term_id'), table_name='course_enrollments')
    op.drop_index(op.f('ix_course_enrollments_course_id'), table_name='course_enrollments')
    op.drop_table('course_enrollments')
    op.drop_index(op.f('ix_terms_user_id'), table_name='terms')
    op.drop_table('terms')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_courses_school_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_created_by'), table_name='courses')
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_users_school_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_schools_normalized_name'), table_name='schools')
    op.drop_table('schools')
    # ### end Alembic commands ###
