"""notification preferences + DECAY_NUDGE (B2 habit digest)

Revision ID: 911eae9c1853
Revises: a1fca0528a36
Create Date: 2026-07-13 02:19:11.614002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '911eae9c1853'
down_revision: Union[str, None] = 'a1fca0528a36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('digest_enabled', sa.Boolean(), nullable=False),
    sa.Column('recognition_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_digest_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_notification_pref_user')
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=False)
    op.sync_enum_values(
        enum_schema='public',
        enum_name='notificationtype',
        new_values=['TEST_GRADED', 'AI_SUMMARY_READY', 'INVITE_ACCEPTED', 'RESOURCE_UPLOADED', 'CLASSMATE_JOINED', 'GENERAL', 'DECAY_NUDGE'],
        affected_columns=[TableReference(table_schema='public', table_name='notifications', column_name='type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='notificationtype',
        new_values=['TEST_GRADED', 'AI_SUMMARY_READY', 'INVITE_ACCEPTED', 'RESOURCE_UPLOADED', 'CLASSMATE_JOINED', 'GENERAL'],
        affected_columns=[TableReference(table_schema='public', table_name='notifications', column_name='type')],
        enum_values_to_rename=[],
    )
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
