"""add google_id to users

Revision ID: cefbe12b1a0a
Revises: v2_features_001
Create Date: 2026-03-06 17:04:42.220564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cefbe12b1a0a'
down_revision: Union[str, None] = 'v2_features_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ai_conversations_course_id'), 'ai_conversations', ['course_id'], unique=False)
    op.create_index(op.f('ix_ai_conversations_topic_id'), 'ai_conversations', ['topic_id'], unique=False)
    op.create_index(op.f('ix_ai_conversations_user_id'), 'ai_conversations', ['user_id'], unique=False)
    op.create_index(op.f('ix_ai_messages_conversation_id'), 'ai_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_classes_owner_id'), 'classes', ['owner_id'], unique=False)
    op.create_index(op.f('ix_classmates_class_id'), 'classmates', ['class_id'], unique=False)
    op.create_index(op.f('ix_classmates_user_id'), 'classmates', ['user_id'], unique=False)
    op.create_index(op.f('ix_course_enrollments_course_id'), 'course_enrollments', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_enrollments_user_id'), 'course_enrollments', ['user_id'], unique=False)
    op.create_index(op.f('ix_course_outlines_course_id'), 'course_outlines', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_outlines_uploaded_by'), 'course_outlines', ['uploaded_by'], unique=False)
    op.add_column('courses', sa.Column('semester_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_courses_created_by'), 'courses', ['created_by'], unique=False)
    op.create_index(op.f('ix_courses_semester_id'), 'courses', ['semester_id'], unique=False)
    op.create_foreign_key(None, 'courses', 'semesters', ['semester_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_fact_checks_resource_id'), 'fact_checks', ['resource_id'], unique=False)
    op.create_index(op.f('ix_pre_class_research_topic_id'), 'pre_class_research', ['topic_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_resource_chunks_resource_id'), 'resource_chunks', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_files_resource_id'), 'resource_files', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resources_topic_id'), 'resources', ['topic_id'], unique=False)
    op.create_index(op.f('ix_resources_uploaded_by'), 'resources', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_study_sessions_topic_id'), 'study_sessions', ['topic_id'], unique=False)
    op.create_index(op.f('ix_study_sessions_user_id'), 'study_sessions', ['user_id'], unique=False)
    op.add_column('test_answers', sa.Column('status', sa.Enum('CORRECT', 'PARTIAL', 'NEEDS_REVIEW', name='answerstatus'), nullable=True))
    op.add_column('test_answers', sa.Column('key_points_covered', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('test_answers', sa.Column('key_points_missed', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_test_answers_attempt_id'), 'test_answers', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_test_answers_question_id'), 'test_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_test_attempts_test_id'), 'test_attempts', ['test_id'], unique=False)
    op.create_index(op.f('ix_test_attempts_user_id'), 'test_attempts', ['user_id'], unique=False)
    op.create_index(op.f('ix_test_questions_test_id'), 'test_questions', ['test_id'], unique=False)
    op.create_index(op.f('ix_tests_course_id'), 'tests', ['course_id'], unique=False)
    op.create_index(op.f('ix_tests_created_by'), 'tests', ['created_by'], unique=False)
    op.create_index(op.f('ix_topics_course_id'), 'topics', ['course_id'], unique=False)
    op.create_index(op.f('ix_user_progress_course_id'), 'user_progress', ['course_id'], unique=False)
    op.create_index(op.f('ix_user_progress_topic_id'), 'user_progress', ['topic_id'], unique=False)
    op.create_index(op.f('ix_user_progress_user_id'), 'user_progress', ['user_id'], unique=False)
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('personality_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('password_reset_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_reset_expires', sa.DateTime(), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'password_reset_expires')
    op.drop_column('users', 'password_reset_token')
    op.drop_column('users', 'personality_tags')
    op.drop_column('users', 'preferences')
    op.drop_column('users', 'google_id')
    op.drop_index(op.f('ix_user_progress_user_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_topic_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_course_id'), table_name='user_progress')
    op.drop_index(op.f('ix_topics_course_id'), table_name='topics')
    op.drop_index(op.f('ix_tests_created_by'), table_name='tests')
    op.drop_index(op.f('ix_tests_course_id'), table_name='tests')
    op.drop_index(op.f('ix_test_questions_test_id'), table_name='test_questions')
    op.drop_index(op.f('ix_test_attempts_user_id'), table_name='test_attempts')
    op.drop_index(op.f('ix_test_attempts_test_id'), table_name='test_attempts')
    op.drop_index(op.f('ix_test_answers_question_id'), table_name='test_answers')
    op.drop_index(op.f('ix_test_answers_attempt_id'), table_name='test_answers')
    op.drop_column('test_answers', 'key_points_missed')
    op.drop_column('test_answers', 'key_points_covered')
    op.drop_column('test_answers', 'status')
    op.drop_index(op.f('ix_study_sessions_user_id'), table_name='study_sessions')
    op.drop_index(op.f('ix_study_sessions_topic_id'), table_name='study_sessions')
    op.drop_index(op.f('ix_resources_uploaded_by'), table_name='resources')
    op.drop_index(op.f('ix_resources_topic_id'), table_name='resources')
    op.drop_index(op.f('ix_resource_files_resource_id'), table_name='resource_files')
    op.drop_index(op.f('ix_resource_chunks_resource_id'), table_name='resource_chunks')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_pre_class_research_topic_id'), table_name='pre_class_research')
    op.drop_index(op.f('ix_fact_checks_resource_id'), table_name='fact_checks')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_index(op.f('ix_courses_semester_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_created_by'), table_name='courses')
    op.drop_column('courses', 'semester_id')
    op.drop_index(op.f('ix_course_outlines_uploaded_by'), table_name='course_outlines')
    op.drop_index(op.f('ix_course_outlines_course_id'), table_name='course_outlines')
    op.drop_index(op.f('ix_course_enrollments_user_id'), table_name='course_enrollments')
    op.drop_index(op.f('ix_course_enrollments_course_id'), table_name='course_enrollments')
    op.drop_index(op.f('ix_classmates_user_id'), table_name='classmates')
    op.drop_index(op.f('ix_classmates_class_id'), table_name='classmates')
    op.drop_index(op.f('ix_classes_owner_id'), table_name='classes')
    op.drop_index(op.f('ix_ai_messages_conversation_id'), table_name='ai_messages')
    op.drop_index(op.f('ix_ai_conversations_user_id'), table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_topic_id'), table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_course_id'), table_name='ai_conversations')
    # ### end Alembic commands ###
