"""cascade handling

Revision ID: c9528675791b
Revises: a0d6d6a28dc1
Create Date: 2026-02-19 17:13:05.189322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9528675791b'
down_revision: Union[str, None] = 'a0d6d6a28dc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_note_chunks_embedding'), table_name='resource_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('idx_notes_is_processed'), table_name='resources')
    op.drop_index(op.f('idx_notes_ocr_provider'), table_name='resources')
    op.drop_index(op.f('idx_notes_topic_id'), table_name='resources')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_notes_topic_id'), 'resources', ['topic_id'], unique=False)
    op.create_index(op.f('idx_notes_ocr_provider'), 'resources', ['ocr_provider'], unique=False)
    op.create_index(op.f('idx_notes_is_processed'), 'resources', ['is_processed'], unique=False)
    op.create_index(op.f('idx_note_chunks_embedding'), 'resource_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###
