"""topic subject_family (B4 subject profiles)

Revision ID: 9aad224787f6
Revises: 911eae9c1853
Create Date: 2026-07-13 02:45:32.229652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9aad224787f6'
down_revision: Union[str, None] = '911eae9c1853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('STEM', 'LANGUAGE', 'HUMANITIES', 'GENERAL', name='subjectfamily').create(op.get_bind())
    op.add_column('topics', sa.Column('subject_family', postgresql.ENUM('STEM', 'LANGUAGE', 'HUMANITIES', 'GENERAL', name='subjectfamily', create_type=False), server_default='GENERAL', nullable=False))
    op.add_column('topics', sa.Column('subject_family_overridden', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'subject_family_overridden')
    op.drop_column('topics', 'subject_family')
    sa.Enum('STEM', 'LANGUAGE', 'HUMANITIES', 'GENERAL', name='subjectfamily').drop(op.get_bind())
    # ### end Alembic commands ###
