"""auth phone-primary: phone required/verified, email optional, otp fields

Revision ID: 2d355456bd16
Revises: f10cdb84d53f
Create Date: 2026-07-12 08:31:20.535896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d355456bd16'
down_revision: Union[str, None] = 'f10cdb84d53f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default so the NOT NULL add is safe even if the table already has rows.
    op.add_column('users', sa.Column('phone_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('phone_otp', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone_otp_expires', sa.DateTime(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'phone_otp_expires')
    op.drop_column('users', 'phone_otp')
    op.drop_column('users', 'phone_verified')
    # ### end Alembic commands ###
