"""retrieval substrate

Revision ID: 6afcc62167b7
Revises: ec36e4fead66
Create Date: 2026-07-05 17:58:05.897626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '6afcc62167b7'
down_revision: Union[str, None] = 'ec36e4fead66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('source_chunk_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'text', name='uq_concept_topic_text')
    )
    op.create_index(op.f('ix_concepts_course_id'), 'concepts', ['course_id'], unique=False)
    op.create_index(op.f('ix_concepts_topic_id'), 'concepts', ['topic_id'], unique=False)
    op.create_table('concept_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('fsrs_card', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('due', sa.DateTime(), nullable=True),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('fsrs_state', sa.Integer(), nullable=True),
    sa.Column('last_review', sa.DateTime(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('last_grade', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'concept_id', name='uq_conceptstate_user_concept')
    )
    op.create_index(op.f('ix_concept_states_concept_id'), 'concept_states', ['concept_id'], unique=False)
    op.create_index(op.f('ix_concept_states_due'), 'concept_states', ['due'], unique=False)
    op.create_index(op.f('ix_concept_states_user_id'), 'concept_states', ['user_id'], unique=False)
    op.create_table('retrieval_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('predicted_confidence', sa.Float(), nullable=True),
    sa.Column('outcome_score', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=8), nullable=True),
    sa.Column('challenge', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retrieval_attempts_concept_id'), 'retrieval_attempts', ['concept_id'], unique=False)
    op.create_index(op.f('ix_retrieval_attempts_created_at'), 'retrieval_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_retrieval_attempts_mode'), 'retrieval_attempts', ['mode'], unique=False)
    op.create_index(op.f('ix_retrieval_attempts_user_id'), 'retrieval_attempts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retrieval_attempts_user_id'), table_name='retrieval_attempts')
    op.drop_index(op.f('ix_retrieval_attempts_mode'), table_name='retrieval_attempts')
    op.drop_index(op.f('ix_retrieval_attempts_created_at'), table_name='retrieval_attempts')
    op.drop_index(op.f('ix_retrieval_attempts_concept_id'), table_name='retrieval_attempts')
    op.drop_table('retrieval_attempts')
    op.drop_index(op.f('ix_concept_states_user_id'), table_name='concept_states')
    op.drop_index(op.f('ix_concept_states_due'), table_name='concept_states')
    op.drop_index(op.f('ix_concept_states_concept_id'), table_name='concept_states')
    op.drop_table('concept_states')
    op.drop_index(op.f('ix_concepts_topic_id'), table_name='concepts')
    op.drop_index(op.f('ix_concepts_course_id'), table_name='concepts')
    op.drop_table('concepts')
    # ### end Alembic commands ###
