"""resource quarantine (merge gate)

Revision ID: f10cdb84d53f
Revises: 6afcc62167b7
Create Date: 2026-07-05 18:15:40.547030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f10cdb84d53f'
down_revision: Union[str, None] = '6afcc62167b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('quarantined', sa.Boolean(), nullable=False))
    op.add_column('resources', sa.Column('quarantine_reason', sa.Text(), nullable=True))
    op.add_column('resources', sa.Column('quarantined_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_resources_quarantined'), 'resources', ['quarantined'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resources_quarantined'), table_name='resources')
    op.drop_column('resources', 'quarantined_at')
    op.drop_column('resources', 'quarantine_reason')
    op.drop_column('resources', 'quarantined')
    # ### end Alembic commands ###
